### ISSUE TITLE
Quite a few aspects don't work on Inkscape 0.92 

### ISSUE THREAD

**Issue by itchka** [sambody/inkscape-guide-tools#13]
Remove all guides fails
Add margins to selected object fails
I didn't try any others.
A shame this extenstion could be extremely useful. A great enhancement would be to be able to set the distance between two selected guides.

**Comment by kfxs** [comment]
Same in Inkscape 0.92.2

I'm receiving this message:

> Traceback (most recent call last):
>   File "add_margin_guides.py", line 162, in <module>
>     effect.affect()
>   File "/usr/share/inkscape/extensions/inkex.py", line 283, in affect
>     self.effect()
>   File "add_margin_guides.py", line 114, in effect
>     factor = inkex.unittouu('1' + self.options.unit)
> AttributeError: 'module' object has no attribute 'unittouu'

**Comment by moassama** [comment]
same here inkscape 0.92.2 5c3e80d


```

> Traceback (most recent call last):
>   File "add_margin_guides.py", line 162, in <module>
>     effect.affect()
>   File "/usr/share/inkscape/extensions/inkex.py", line 283, in affect
>     self.effect()
>   File "add_margin_guides.py", line 114, in effect
>     factor = inkex.unittouu('1' + self.options.unit)
> AttributeError: 'module' object has no attribute 'unittouu'

```
